### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by isbkch** [nikoma/apphera-sense#1]
Installation went successful, MongoDB running, when I hit http://localhost:3000/ the page is blank.

I'm getting these as logs:

```
GET / 304 5.552 ms - -
GET /lib/bootstrap/dist/css/bootstrap.css 304 9.356 ms - -
GET /lib/bootstrap/dist/css/bootstrap-theme.css 304 9.077 ms - -
GET /modules/core/css/core.css 304 8.328 ms - -
GET /modules/core/css/style.css 304 8.155 ms - -
GET /lib/jquery/dist/jquery.min.js 304 7.390 ms - -
GET /modules/users/css/users.css 304 7.839 ms - -
GET /lib/angular/angular.js 304 1.868 ms - -
....
```

But nothing shows on the page.

**Comment by isbkch** [comment]
At least two modules missing "angular-paginate-anything" and "angular-img-fallback-master". you should add them to bower.. 

Code is bad, many "undefined" javascript and Angular related errors..

I managed to get it to work but Keywords page is full of errors making it unusable

**Comment by nikoma** [comment]
Yes, that's true. I apologize. Best in these cases would be sending a pull request and are all happier just in case you want to help a bit. As we did many other dashboards we will now work a bit on this one now to have a demo version so you should not see many errors here very soon..
